spring.application.name=webgis_service
server.port=8089

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/webgis-study
spring.datasource.username=postgres
spring.datasource.password=tjh2834025757
spring.datasource.driver-class-name=org.postgresql.Driver
